VidlyTakeTwo/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VidlyTakeTwo.Controllers
{
    public class RentalsController : Controller
    {
        public ActionResult New()
        {
            return View();
        }
    }
}

VidlyTakeTwo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar"); @*Here we are rendering the partial view _NavBar*@
    <div class="container body-content">
        @RenderBody()  @{// what we put in our views will be placed here when the view
// is rendered

        }
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)@{ //RenderSection allows us to add a script section in
    //our views. Look at end of CustomerForm for an example of script.

    }
    }
</body>

</html>

VidlyTakeTwo/Views/Shared/_NavBar.cshtml
@*
   A partial view is like a small view that we can use in different views. BUT partial 
    views are not necessarily for reusing markup. Sometimes, we can use them to break 
    up a view into smaller, more maintainable partial views.
    
    By convention, we prefix partial view names with an underscore.   
*@
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                @*@ <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            Html.ActionLink CREATES A LINK TO AN ACTION IN A CONTROLLER*@
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>